# Generated by Django 5.0.2 on 2024-03-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wins',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ongame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
