# Generated by Django 5.0.2 on 2024-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
