# Generated by Django 5.0.2 on 2024-05-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked',
            field=models.ManyToManyField(blank=True, to='backend.userprofile'),
        ),
    ]
